using FitBook.Model.Requests.Reports;
using FitBook.Services.Database;
using FitBook.Services.Interfaces;
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuestPDF.Fluent;

namespace FitBook.Services.Reports;

public class ReportService : IReportService
{
    private readonly FitBookDbContext _dbContext;
    private readonly ICurrentUserService _currentUserService;
    private readonly IValidator<ReservationsReportRequest> _reservationsReportValidator;
    private readonly ILogger<ReportService> _logger;

    public ReportService(
        FitBookDbContext dbContext,
        ICurrentUserService currentUserService,
        IValidator<ReservationsReportRequest> reservationsReportValidator,
        ILogger<ReportService> logger)
    {
        _dbContext = dbContext;
        _currentUserService = currentUserService;
        _reservationsReportValidator = reservationsReportValidator;
        _logger = logger;
    }

    public async Task<byte[]> GenerateReservationsReportAsync(ReservationsReportRequest request, CancellationToken cancellationToken = default)
    {
        await _reservationsReportValidator.ValidateAndThrowAsync(request, cancellationToken);

        var rows = await _dbContext.Reservations
            .Where(r => r.ReservedAtUtc >= request.FromUtc && r.ReservedAtUtc <= request.ToUtc)
            .OrderBy(r => r.ReservedAtUtc)
            .Select(r => new ReservationReportRow
            {
                UserFullName = r.UserAccount!.FirstName + " " + r.UserAccount.LastName,
                TrainingName = r.TrainingTerm!.Training!.Name,
                TrainingTermStartUtc = r.TrainingTerm.StartTimeUtc,
                Status = r.Status,
                ReservedAtUtc = r.ReservedAtUtc,
            })
            .ToListAsync(cancellationToken);

        var document = new ReservationsReportDocument(rows, request.FromUtc, request.ToUtc, DateTime.UtcNow);
        var pdfBytes = document.GeneratePdf();

        _logger.LogInformation(
            "Reservations report generated by admin {AdminId} for period {FromUtc} - {ToUtc}. Rows: {RowCount}.",
            _currentUserService.GetRequiredUserId(),
            request.FromUtc,
            request.ToUtc,
            rows.Count);

        return pdfBytes;
    }

    public async Task<byte[]> GenerateTrainingPopularityReportAsync(CancellationToken cancellationToken = default)
    {
        var rows = await _dbContext.Trainings
            .Select(t => new TrainingPopularityReportRow
            {
                TrainingName = t.Name,
                CategoryName = t.TrainingCategory!.Name,
                ReservationCount = t.TrainingTerms.SelectMany(tt => tt.Reservations).Count(),
            })
            .OrderByDescending(r => r.ReservationCount)
            .ToListAsync(cancellationToken);

        var document = new TrainingPopularityReportDocument(rows, DateTime.UtcNow);
        var pdfBytes = document.GeneratePdf();

        _logger.LogInformation(
            "Training popularity report generated by admin {AdminId}. Trainings: {RowCount}.",
            _currentUserService.GetRequiredUserId(),
            rows.Count);

        return pdfBytes;
    }
}
