// <auto-generated />
using System;
using FitBook.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitBook.Services.Migrations
{
    [DbContext(typeof(FitBookDbContext))]
    [Migration("20260713180528_NewsItemImageUrlRequired")]
    partial class NewsItemImageUrlRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitBook.Services.Database.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DifficultyLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Beginner",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Intermediate",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Advanced",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Halls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationDescription = "Ground Floor, Zone A",
                            Name = "Main Gym Hall"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationDescription = "First Floor, Zone B",
                            Name = "Yoga & Pilates Studio"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationDescription = "First Floor, Zone C",
                            Name = "Spinning Room"
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.MembershipPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("IncludedBenefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SavingsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("MembershipPackages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            IncludedBenefits = "Access to main hall, 3 group trainings per week.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "1 Month Basic",
                            Price = 50.00m,
                            SavingsAmount = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 90,
                            IncludedBenefits = "Unlimited group trainings, sauna access, 1 free personal session.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "3 Month Premium",
                            Price = 120.00m,
                            SavingsAmount = 30.00m
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.MembershipPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.Property<int>("UserMembershipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentIntentId")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.HasIndex("UserMembershipId", "Status");

                    b.ToTable("MembershipPayments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50.00m,
                            CreatedAtUtc = new DateTime(2026, 5, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "BAM",
                            PaidAtUtc = new DateTime(2026, 5, 30, 10, 5, 0, 0, DateTimeKind.Utc),
                            PaymentIntentId = "pi_1234567890",
                            PaymentProvider = "Stripe",
                            Status = 2,
                            TransactionReference = "tx_998877",
                            UserAccountId = 2,
                            UserMembershipId = 1
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAtUtc");

                    b.ToTable("NewsItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "We are thrilled to announce that our new premium Yoga & Pilates studio on the first floor is now open for bookings.",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "uploads/news/yoga_opening.jpg",
                            IsActive = true,
                            PublishedAtUtc = new DateTime(2026, 6, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Grand Opening of our Yoga Studio!"
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.RecommendationSignal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("SignalType")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("TrainingCategoryId");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserAccountId", "SignalType");

                    b.ToTable("RecommendationSignals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReservationId = 1,
                            SignalType = 4,
                            TrainingCategoryId = 1,
                            TrainingId = 1,
                            UserAccountId = 2,
                            Weight = 1.0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 6, 26, 13, 0, 0, 0, DateTimeKind.Utc),
                            ReservationId = 2,
                            SignalType = 4,
                            TrainingCategoryId = 2,
                            TrainingId = 2,
                            UserAccountId = 2,
                            Weight = 1.0m
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastStatusChangedByUserAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTermId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastStatusChangedByUserAccountId");

                    b.HasIndex("TrainingTermId", "Status");

                    b.HasIndex("UserAccountId", "TrainingTermId")
                        .IsUnique()
                        .HasFilter("[Status] IN (1, 2)");

                    b.ToTable("Reservations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAtUtc = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            ConfirmedAtUtc = new DateTime(2026, 6, 21, 15, 10, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservedAtUtc = new DateTime(2026, 6, 21, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TrainingTermId = 1,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 2,
                            CompletedAtUtc = new DateTime(2026, 6, 26, 13, 0, 0, 0, DateTimeKind.Utc),
                            ConfirmedAtUtc = new DateTime(2026, 6, 22, 16, 5, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservedAtUtc = new DateTime(2026, 6, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TrainingTermId = 2,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 3,
                            ConfirmedAtUtc = new DateTime(2026, 6, 23, 10, 15, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservedAtUtc = new DateTime(2026, 6, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TrainingTermId = 3,
                            UserAccountId = 2
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.ReservationStatusAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserAccountId");

                    b.HasIndex("ReservationId", "ChangedAtUtc");

                    b.ToTable("ReservationStatusAudits", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAtUtc = new DateTime(2026, 6, 21, 15, 10, 0, 0, DateTimeKind.Utc),
                            ChangedByUserAccountId = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewStatus = 2,
                            PreviousStatus = 1,
                            Reason = "Auto-confirmed on successful payment and active membership check",
                            ReservationId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChangedAtUtc = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserAccountId = 5,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewStatus = 4,
                            PreviousStatus = 2,
                            Reason = "Marked as completed after class finish",
                            ReservationId = 1
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.SystemNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "IsRead");

                    b.ToTable("SystemNotifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Your reservation for Vinyasa Yoga has been successfully confirmed.",
                            CreatedAtUtc = new DateTime(2026, 6, 23, 10, 15, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            NotificationType = 2,
                            Title = "Reservation Confirmed",
                            UserAccountId = 2
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Trainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Certified trainer with 8+ years of experience in athletic training.",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "John",
                            ImageUrl = "uploads/trainers/trainer1.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            LastName = "Doe",
                            Specialization = "Strength & Conditioning",
                            UserAccountId = 3
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Passionate about helping people find balance and flexibility.",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Jane",
                            ImageUrl = "uploads/trainers/trainer2.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            LastName = "Smith",
                            Specialization = "Yoga & Pilates",
                            UserAccountId = 4
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Energy-packed HIIT workouts to keep you burning calories.",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Mike",
                            ImageUrl = "uploads/trainers/trainer3.jpg",
                            IsActive = true,
                            IsAvailable = true,
                            LastName = "Jones",
                            Specialization = "Cardio & HIIT",
                            UserAccountId = 5
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TrainingCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("Name");

                    b.HasIndex("TrainingCategoryId");

                    b.ToTable("Trainings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High Intensity Interval Training to boost metabolism.",
                            DifficultyLevelId = 2,
                            DurationMinutes = 45,
                            IsActive = true,
                            MaxParticipants = 20,
                            Name = "HIIT Blast",
                            TrainingCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn and execute proper barbell techniques.",
                            DifficultyLevelId = 3,
                            DurationMinutes = 60,
                            IsActive = true,
                            MaxParticipants = 10,
                            Name = "Power Lifting",
                            TrainingCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flowing sequences of yoga poses with breath control.",
                            DifficultyLevelId = 1,
                            DurationMinutes = 60,
                            IsActive = true,
                            MaxParticipants = 15,
                            Name = "Vinyasa Yoga",
                            TrainingCategoryId = 3
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainingCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Workouts designed to improve heart health and stamina.",
                            IsActive = true,
                            Name = "Cardio"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Resistance training designed to build muscle mass.",
                            IsActive = true,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yoga, stretching, and mindfulness practices.",
                            IsActive = true,
                            Name = "Mind & Body"
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId", "Name")
                        .IsUnique();

                    b.ToTable("TrainingEquipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRequired = true,
                            Name = "Kettlebell",
                            Note = "Recommended 8kg-16kg",
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRequired = true,
                            Name = "Barbell Set",
                            Note = "Belts provided in hall",
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRequired = false,
                            Name = "Yoga Mat",
                            Note = "Mats are available in studio, or bring your own",
                            TrainingId = 3
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("TrainingId", "StartTimeUtc");

                    b.HasIndex("TrainerId", "StartTimeUtc", "EndTimeUtc");

                    b.ToTable("TrainingTerms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTimeUtc = new DateTime(2026, 6, 25, 10, 45, 0, 0, DateTimeKind.Utc),
                            HallId = 3,
                            IsActive = true,
                            MaxParticipants = 20,
                            StartTimeUtc = new DateTime(2026, 6, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TrainerId = 3,
                            TrainingId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTimeUtc = new DateTime(2026, 6, 26, 13, 0, 0, 0, DateTimeKind.Utc),
                            HallId = 1,
                            IsActive = true,
                            MaxParticipants = 10,
                            StartTimeUtc = new DateTime(2026, 6, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TrainerId = 1,
                            TrainingId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTimeUtc = new DateTime(2026, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            HallId = 2,
                            IsActive = true,
                            MaxParticipants = 15,
                            StartTimeUtc = new DateTime(2026, 7, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TrainerId = 2,
                            TrainingId = 3
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("UserAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fitbook.com",
                            FirstName = "System",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$absRakK74SEnr3k6jdjqHeTmEa7SE2m2/0J09n4aSg/kLY1jGVW46",
                            PhoneNumber = "+38761111222",
                            ProfileImageUrl = "uploads/users/admin.jpg",
                            Role = "Admin",
                            Username = "desktop"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@fitbook.com",
                            FirstName = "John",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Client",
                            PasswordHash = "$2a$11$absRakK74SEnr3k6jdjqHeTmEa7SE2m2/0J09n4aSg/kLY1jGVW46",
                            PhoneNumber = "+38761333444",
                            ProfileImageUrl = "uploads/users/john.jpg",
                            Role = "User",
                            Username = "mobile"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "johndoe@fitbook.com",
                            FirstName = "John",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$absRakK74SEnr3k6jdjqHeTmEa7SE2m2/0J09n4aSg/kLY1jGVW46",
                            PhoneNumber = "+38761555001",
                            ProfileImageUrl = "uploads/trainers/trainer1.jpg",
                            Role = "Trainer",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "janesmith@fitbook.com",
                            FirstName = "Jane",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$absRakK74SEnr3k6jdjqHeTmEa7SE2m2/0J09n4aSg/kLY1jGVW46",
                            PhoneNumber = "+38761555002",
                            ProfileImageUrl = "uploads/trainers/trainer2.jpg",
                            Role = "Trainer",
                            Username = "janesmith"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mikejones@fitbook.com",
                            FirstName = "Mike",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Jones",
                            PasswordHash = "$2a$11$absRakK74SEnr3k6jdjqHeTmEa7SE2m2/0J09n4aSg/kLY1jGVW46",
                            PhoneNumber = "+38761555003",
                            ProfileImageUrl = "uploads/trainers/trainer3.jpg",
                            Role = "Trainer",
                            Username = "mikejones"
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.UserMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MembershipPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextPaymentDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPackageId");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("UserAccountId", "IsActive");

                    b.ToTable("UserMemberships", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDateUtc = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MembershipPackageId = 1,
                            NextPaymentDateUtc = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDateUtc = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            UserAccountId = 2
                        });
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.MembershipPayment", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "UserAccount")
                        .WithMany("Payments")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.UserMembership", "UserMembership")
                        .WithMany("Payments")
                        .HasForeignKey("UserMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");

                    b.Navigation("UserMembership");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.RecommendationSignal", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.Reservation", "Reservation")
                        .WithMany("RecommendationSignals")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitBook.Services.Database.Entities.TrainingCategory", "TrainingCategory")
                        .WithMany("RecommendationSignals")
                        .HasForeignKey("TrainingCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.Training", "Training")
                        .WithMany("RecommendationSignals")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "UserAccount")
                        .WithMany("RecommendationSignals")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Training");

                    b.Navigation("TrainingCategory");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.RefreshToken", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Reservation", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "LastStatusChangedByUserAccount")
                        .WithMany("ReservationStatusChanged")
                        .HasForeignKey("LastStatusChangedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitBook.Services.Database.Entities.TrainingTerm", "TrainingTerm")
                        .WithMany("Reservations")
                        .HasForeignKey("TrainingTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "UserAccount")
                        .WithMany("Reservations")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastStatusChangedByUserAccount");

                    b.Navigation("TrainingTerm");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.ReservationStatusAudit", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "ChangedByUserAccount")
                        .WithMany("ReservationStatusAudits")
                        .HasForeignKey("ChangedByUserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.Reservation", "Reservation")
                        .WithMany("StatusAudits")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUserAccount");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.SystemNotification", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "UserAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Trainer", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "UserAccount")
                        .WithOne("Trainer")
                        .HasForeignKey("FitBook.Services.Database.Entities.Trainer", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Training", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Trainings")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.TrainingCategory", "TrainingCategory")
                        .WithMany("Trainings")
                        .HasForeignKey("TrainingCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("TrainingCategory");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingEquipment", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.Training", "Training")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingTerm", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.Hall", "Hall")
                        .WithMany("TrainingTerms")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.Trainer", "Trainer")
                        .WithMany("TrainingTerms")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.Training", "Training")
                        .WithMany("TrainingTerms")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Trainer");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.UserMembership", b =>
                {
                    b.HasOne("FitBook.Services.Database.Entities.MembershipPackage", "MembershipPackage")
                        .WithMany("UserMemberships")
                        .HasForeignKey("MembershipPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBook.Services.Database.Entities.UserAccount", "UserAccount")
                        .WithMany("Memberships")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipPackage");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.DifficultyLevel", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Hall", b =>
                {
                    b.Navigation("TrainingTerms");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.MembershipPackage", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Reservation", b =>
                {
                    b.Navigation("RecommendationSignals");

                    b.Navigation("StatusAudits");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Trainer", b =>
                {
                    b.Navigation("TrainingTerms");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.Training", b =>
                {
                    b.Navigation("EquipmentItems");

                    b.Navigation("RecommendationSignals");

                    b.Navigation("TrainingTerms");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingCategory", b =>
                {
                    b.Navigation("RecommendationSignals");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.TrainingTerm", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.UserAccount", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("RecommendationSignals");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReservationStatusAudits");

                    b.Navigation("ReservationStatusChanged");

                    b.Navigation("Reservations");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitBook.Services.Database.Entities.UserMembership", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
